version: '3.7'

services:

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: StudentsWhoSitDB
      DATABASE_URL: postgres://postgres:1234@db:5432/StudentsWhoSitDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5455:5432

  frontend:
    container_name: frontend
    build:
      context: sws-frontend
      dockerfile: Dockerfile
    #volumes:
    #  - '.:/app'
    #  - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  api:
    container_name: api
    build:
      context: sws-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

volumes:
  postgres_data: