version: '3.7'

services:

  postgres-db:
    container_name: postgres-db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: StudentsWhoSitDB
      DATABASE_URL: postgres://postgres:1234@postgres-db:5432/StudentsWhoSitDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5455:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: benjamin.m.peng@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password12345
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  react-frontend:
    container_name: react-frontend
    build:
      context: sws-frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  go-api:
    container_name: go-api
    build:
      context: sws-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

volumes:
  postgres_data:
  pgadmin_data: